---
exclude_paths:
- test/*
- docs/*
- examples/*
- vendor/*
ratings:
  paths:
  - "**.php"
engines:
  phpmd:
    enabled: true
    checks:
      Controversial/Superglobals:
        enabled: false
  phpcodesniffer:
    enabled: true
    checks:
      PSR2 Methods FunctionCallSignature Indent:
        enabled: false
      Generic WhiteSpace ScopeIndent Incorrect:
        enabled: false
