<?php

namespace Chippyash\Test\Validation\Common;

use Chippyash\Validation\Common\ZFValidator as ZendBaseValidator;
use Chippyash\Validation\Messenger;
use PHPUnit\Framework\TestCase;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-12-08 at 19:09:41.
 */
class ZendTest extends TestCase
{
    /**
     * Default set of validators
     *
     * @var array
     */
    /**
     * a set of validators
     *
     * @var array
     */
    protected $invokableClasses = array(
        'alnum'                    => 'Laminas\I18n\Validator\Alnum',
        'alpha'                    => 'Laminas\I18n\Validator\Alpha',
        'barcode'                  => 'Laminas\Validator\Barcode',
        'between'                  => 'Laminas\Validator\Between',
        'float'                    => 'Laminas\I18n\Validator\IsFloat',
        'int'                      => 'Laminas\I18n\Validator\IsInt',
        'postcode'                 => 'Laminas\I18n\Validator\PostCode',
    );

    /**
     * @var Messenger
     */
    protected $messenger;

    public function setUp(): void
    {
        $this->messenger = new Messenger();
    }

    /**
     * @dataProvider zendValidators
     * @requires extension intl
     */
    public function testWillReturnCorrectResponseForTestDataSetViaMagicInvokeMethod($baseName, $constructParams, $trueValue, $falseValue)
    {
        $className = $this->invokableClasses[$baseName];
        $object = new ZendBaseValidator(new $className($constructParams));
        $this->assertTrue($object($trueValue, $this->messenger));
        $this->assertFalse($object($falseValue, $this->messenger));
    }

    /**
     * @dataProvider zendValidators
     * @requires extension intl
     */
    public function testWillReturnCorrectResponseForTestDataSetViaIsValidMethod($baseName, $constructParams, $trueValue, $falseValue)
    {
        $className = $this->invokableClasses[$baseName];
        $object = new ZendBaseValidator(new $className($constructParams));
        $this->assertTrue($object->isValid($trueValue));
        $this->assertFalse($object->isValid($falseValue));
    }

    public function testYouCanGetTheUnderlyingZendErrorMessages()
    {
        $object = new ZendBaseValidator(new \Laminas\I18n\Validator\Alnum());
        $this->assertFalse($object->isValid(''));
        $this->assertEquals(array('The input is an empty string'), $object->getMessages());
    }

    /**
     * Tests of Laminas validators
     * We are not testing all of them!
     *
     */
    public function zendValidators()
    {
        return array(
            array('alnum', false,'hw1234',''),
            array('alpha', null,'abcd','1234'),
            array('barcode', array('adapter'=> 'Code25interleaved'),'1234567895','HHHHHH'),
            array('between', array('min'=>2,'max'=>5),3,6),
            array('float', array(),'1234.56','ah67.3'),
            array('int', array(),'12345','1d456'),
            array('postcode', array('locale'=>'en-GB'),'NN10 6AG','ZZ2 FY1'),
        );
    }
}
